const sampleRestaurants = [
    {
      title: "Pizza Palace",
      imageUrl: "https://example.com/images/pizza-palace.jpg",
      foods: ["Pizza", "Pasta", "Garlic Bread"],
      time: "10:00 AM - 11:00 PM",
      pickup: true,
      delivery: true,
      isOpen: true,
      logoUrl: "https://example.com/logos/pizza-palace-logo.png",
      rating: 4.6,
      ratingCount: 1284,
      code: "PP123",
      coords: { lat: 40.712776, lng: -74.005974 },
    },
    {
      title: "Sushi Station",
      imageUrl: "https://example.com/images/sushi-station.jpg",
      foods: ["Sushi", "Ramen", "Tempura"],
      time: "11:30 AM - 10:00 PM",
      pickup: false,
      delivery: true,
      isOpen: false,
      logoUrl: "https://example.com/logos/sushi-station-logo.png",
      rating: 4.8,
      ratingCount: 982,
      code: "SS456",
      coords: { lat: 34.052235, lng: -118.243683 },
    },
    {
      title: "Burger Bros",
      imageUrl: "https://example.com/images/burger-bros.jpg",
      foods: ["Burgers", "Fries", "Shakes"],
      time: "9:00 AM - 12:00 AM",
      pickup: true,
      delivery: false,
      isOpen: true,
      logoUrl: "https://example.com/logos/burger-bros-logo.png",
      rating: 4.3,
      ratingCount: 547,
      code: "BB789",
      coords: { lat: 41.878113, lng: -87.629799 },
    },
    {
      title: "Taco Town",
      imageUrl: "https://example.com/images/taco-town.jpg",
      foods: ["Tacos", "Quesadillas", "Burritos"],
      time: "10:00 AM - 9:00 PM",
      pickup: true,
      delivery: true,
      isOpen: true,
      logoUrl: "https://example.com/logos/taco-town-logo.png",
      rating: 4.0,
      ratingCount: 312,
      code: "TT321",
      coords: { lat: 29.760427, lng: -95.369804 },
    },
    {
      title: "Green Garden",
      imageUrl: "https://example.com/images/green-garden.jpg",
      foods: ["Salads", "Wraps", "Smoothies"],
      time: "8:00 AM - 8:00 PM",
      pickup: true,
      delivery: true,
      isOpen: false,
      logoUrl: "https://example.com/logos/green-garden-logo.png",
      rating: 4.7,
      ratingCount: 759,
      code: "GG654",
      coords: { lat: 37.774929, lng: -122.419418 },
    }
  ];
  
  // To insert into MongoDB:
  